---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-storage
#  labels:
#    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /fabric8/fabric8-docker-registry-storage