#%RAML 1.0 Trait

queryParameters:
  expiresIn:
    description: |
      The <<resourcePathName|!singularize>> expires
      within this many days (either sooner or exactly then).
    type: integer
    required: false
