
queryParameters:
  isPending:
    description: |
      The <<resourcePathName|!singularize>> is pending.
    type: boolean
    required: false
  isModified:
    description: |
      The <<resourcePathName|!singularize>> is modified.
    type: boolean
    required: false
