version: '3'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    container_name: k8s-zookeeper
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/zookeeper/bin/zkServer.sh", "status"]
  kafka:
    container_name: k8s-kafka
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--zookeeper", "zookeeper:2181", "--list"]
    volumes:
       - ./kafka-logs:/tmp/kafka-logs
  rulerunner-service:
    container_name: k8s-rulerunner
    image: 'epam.com/rulerunner-service'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    networks:
      - app-tier
    depends_on:
      - kafka

