version: '3'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost"]
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    #command: >
    #  /opt/bitnami/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --topic rulerunner-output --partitions 1 --replication-factor 1
  rulerunner-service:
    image: 'epam.com/rulerunner-service'
    ports:
      - '8080:8080'
    environment:
      - kafka.connection.host=kafka
      - kafka.connection.port=9092
    networks:
      - app-tier
    depends_on:
      - kafka
