apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: debug
  selector:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
