# Default values for service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
image:
  name:
  repository: epam.com
  tag: latest
  pullPolicy: Never

service:
#  type: ClusterIP
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /

  wildCardDomain: "<minikube_ip/kubernetes_nginx_ingress_host>.nip.io"

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
containers:
  initialDelaySeconds: 120
  periodSeconds: 15

resources:
  limits:
    memory: "512Mi"
  requests:
    memory: "128Mi"

java:
  opts: "-Xms64M -Xmx512M"

nodeSelector: {}

imagePullSecret:

tolerations: []

affinity: {}
