#%RAML 1.0 DataType

description: Money amount (sum and currency)
properties:
  amount:
    description: The amount in the given currency
    type: number
  currency:
    description: The currency
    type: string
