#%RAML 1.0 DataType

description: Card block
properties:
  blockType:
    type: string
    required: true
  addedAtDateTime:
    type: datetime-only
    required: true
  effectiveUntilDateTime:
    type: datetime-only
    required: false
