#%RAML 1.0 DataType

types:
  CardUpdate: !include CardUpdate.raml
type: CardUpdate
description: Card attributes that are relevant from card management point of view
properties:
    mainAccount:
        description: |
            The main account this card is assigned to. The card might be
            assigned to another account, but the main account never changes
            and thus could be used to group the main card and the
            additional cards.
    serialNumber:
        description: |
            The serial number of the card; increased whenever a new card
            with the same card number is issued.
        required: true
    expiryYear:
        description: The year after that the card expires.
        type: string
        pattern: \d{4}
    expiryMonth:
        description: The month after that the card expires.
        type: string
        pattern: \d{2}