#%RAML 1.0 DataType

description: Fees associated with the card
properties:
  yearlyFeeAmount:
    description: The yearly fee of the card
    type: Amount
    required: false
  monthlyFeeAmount:
    description: The monthly fee of the card
    type: Amount
    required: false
