#%RAML 1.0 DataType

description: Phone number
properties:
  countryCode:
      type: string
      required: true
  areaCode:
      type: string
      required: true
  phoneNumber:
      type: string
      required: true
  extension:
      type: string
      required: false