#%RAML 1.0 DataType

description: Region-level geoblock configuration
properties:
  cardId:
    description: Card identifier as a composite of client identifier and the last four digits of the card
    type: string
    required: true
  regionCode:
    description: Code of a region
    type: string
    required: true
  blocked:
    description: Boolean flag that represents whether the card is blocked in the given country
    type: boolean
    required: true
  expirationDate:
    description: Expiration date of the blocking in the following format (YYYY-MM-DD).
    type: date-only
    required: false