apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  selector:
    run: postgres
  ports:
    - name: port1
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32345
  type: NodePort