#!/bin/sh
hookFile="$BASH_SOURCE"
echo pre-push hook running sonarqube
echo "Setting hook's read-only attribute."
chmod -w $hookFile
branch=$(git rev-parse --abbrev-ref HEAD)
./gradlew test testComponent sonarqube
rc=$?
echo "Removing hook's read-only attribute."
chmod +w $hookFile
if [[ $rc != 0 ]]; then exit $rc; fi