---
- name: Install Elasticsearch
  hosts: ecsb00101a05.epam.com
  become: true
    mount_path: /var/lib/elasticsearch/
    logical_volume: elastisearch_data
    es_api_host: 10.253.129.44
    es_api_port: 9200
    es_heap_size: 4g
  roles:
  - { role: ava.noswap, tags: swap }
  - { role: ava.disks, tags: disks }
  - { role: elastic.elasticsearch, es_instance_name: "ecsb00101a05.epam.com", tags: elasticsearch, 
    es_config: {
        node.name: "ecsb00101a05.epam.com", 
        cluster.name: "test-cluster", 
        discovery.zen.ping.unicast.hosts: "localhost:9301", 
        http.port: 9200, 
        transport.tcp.port: 9300, 
        network.host: "10.253.129.44",
        node.data: true, 
        node.master: true, 
        bootstrap.memory_lock: true, 
        } 
    }    
