/**
* NOTE: This class is auto generated by the swagger code generator program (2.3.1).
* https://github.com/swagger-api/swagger-codegen
* Do not edit the class manually.
*/
package com.epam.rulerunner.order.server;

import com.epam.rulerunner.order.model.Order;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

public interface OrdersApi {

    OrdersApiDelegate getDelegate();

    @RequestMapping(value = "/orders",
            produces = { "application/json" },
            consumes = { "application/vnd.epam.order.management+json" },
            method = RequestMethod.POST)
    default ResponseEntity<Void> sendOrder(@Valid @RequestBody Order body) {
        return getDelegate().sendOrder(body);
    }

    @RequestMapping(value = "/orders/{orderId}",
            produces = { "application/vnd.epam.order.management+json" },
            method = RequestMethod.GET)
    default ResponseEntity<Order> getOrders(@PathVariable("orderId") String orderId ) {
        return getDelegate().getOrders(orderId);
    }

    @RequestMapping(value = "/orders",
            produces = { "application/vnd.epam.order.management+json" },
            method = RequestMethod.GET)
    default ResponseEntity<List<Order>> getOrders() {
        return getDelegate().getOrders();
    }
}
